baseurl = "http://replace-this-with-your-hugo-site.com/"
title = "Quckoo"
languageCode = "en-us"
theme = "universal"

[params]
  style = "blue"
  logo = "img/quckoo_logo.png"
  #about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
  copyright = "Copyright (c) 2015 - 2016, Antonio Alonso Dominguez; all rights reserved."

[[params.menu]]
  name = "news"
  url = "/"
  weight = 1

[[params.menu]]
  name = "Documentation"
  url = "/docs"
  weight = 2

[[params.menu]]
  name = "Github"
  url = "https://www.github.com/alonsodomin/quckoo"
  weight = 2

[params.carousel]
  enable = true

[params.features]
  enable = true

[params.recent_posts]
  enable = false
  title = "Latest news"
